import type { Ticket } from "./TicketBoard";

export const STATIC_TICKETS: Ticket[] = [
  // TM Q1
  { key: "TM-814",  summary: "[파트너] [29Connect] 일반 할인 셀프서비스 도입",                           status: "론치완료",       assignee: "양유주",  eta: "2026-03-16", type: "Initiative", project: "TM" },
  { key: "TM-1241", summary: "[쿠폰] [29Connect] 파트너 쿠폰 대시보드 제공",                             status: "개발중",         assignee: "양유주",  eta: "2026-06-08", type: "Initiative", project: "TM",
    roles: [
      { role: "기획",   person: "양유주",   start: "2026-01-05", end: "2026-03-01", status: "완료" },
      { role: "디자인", person: "미정",     start: "2026-02-15", end: "2026-03-31", status: "완료" },
      { role: "개발BE", person: "미정",     start: "2026-03-20", end: "2026-05-31", status: "진행중" },
      { role: "개발FE", person: "미정",     start: "2026-04-01", end: "2026-06-08", status: "예정" },
      { role: "QA",     person: "미정",     start: "2026-05-20", end: "2026-06-08", status: "예정" },
    ],
  },
  { key: "TM-1244", summary: "[티켓] [29CM] 티켓 양도 기능 도입 - 지정좌석예매, Iter. 2",                status: "론치완료",       assignee: "양유주",  eta: "2026-03-05", type: "Initiative", project: "TM" },
  { key: "TM-1246", summary: "[CS] [29CM] AI 챗봇 파일럿 구축 - PoC",                                   status: "론치완료",       assignee: "좌예슬",  eta: "2026-03-27", type: "Initiative", project: "TM" },
  { key: "TM-1247", summary: "[티켓] [29CM] 선예매 기능 도입 - 지정좌석예매, Iter. 2",                   status: "론치완료",       assignee: "양유주",  eta: "2026-02-05", type: "Initiative", project: "TM" },
  { key: "TM-1283", summary: "[장바구니] [29CM] 할인 UX 고도화 - Phase 2. Urgency 강화",                 status: "HOLD",           assignee: "정유민",  eta: "2026-01-30", type: "Initiative", project: "TM" },
  { key: "TM-1297", summary: "[쿠폰] [29CM] 브랜드홈 쿠폰 노출 강화",                                    status: "론치완료",       assignee: "백수지",  eta: "2026-01-07", type: "Initiative", project: "TM" },
  { key: "TM-1298", summary: "[정책] [29CM] 스토어 채널 파트너 일반할인 셀프서비스",                      status: "론치완료",       assignee: "양유주",  eta: "2026-01-16", type: "Initiative", project: "TM" },
  { key: "TM-1305", summary: "[파트너] [29Connect] 파트너 대시보드 리뉴얼",                               status: "디자인중",       assignee: "정유민",  eta: "2026-04-30", type: "Initiative", project: "TM" },
  { key: "TM-1357", summary: "[클레임] [29CM] 클레임 신규 정책 시스템화 - 무배당발 빠른교환",             status: "론치완료",       assignee: "좌예슬",  eta: "2026-02-17", type: "Initiative", project: "TM" },
  { key: "TM-1358", summary: "[클레임] [29CM] 상품 준비중 취소 기능 도입",                                status: "론치완료",       assignee: "좌예슬",  eta: "2026-01-14", type: "Initiative", project: "TM" },
  { key: "TM-1360", summary: "[결제] [29CM] 결제수단 개편 - 무신사페이 외 간편결제",                      status: "론치완료",       assignee: "정유민",  eta: "2026-01-09", type: "Initiative", project: "TM" },
  { key: "TM-1362", summary: "[보안] [29Connect] API 인증체계 개선 - Static Key V2 전환",                 status: "론치완료",       assignee: "윤정오",  eta: "2026-02-27", type: "Initiative", project: "TM" },
  { key: "TM-1363", summary: "[카탈로그] [29CM] 상품 속성 집계 고도화 - 색상 분류 체계 개선",             status: "론치완료",       assignee: "백수지",  eta: "2026-01-09", type: "Initiative", project: "TM" },
  { key: "TM-1369", summary: "[주문] [29CM] 선물하기 고도화 - Phase 2",                                   status: "론치완료",       assignee: "좌예슬",  eta: "2026-03-06", type: "Initiative", project: "TM" },
  { key: "TM-1373", summary: "[카탈로그] [29CM] 상품 SEO 개선",                                           status: "론치완료",       assignee: "백수지",  eta: "2026-02-13", type: "Initiative", project: "TM" },
  { key: "TM-1376", summary: "[정산] [29CM] 포인트/적립금 이원화",                                        status: "론치완료",       assignee: "정윤수",  eta: "2026-01-16", type: "Initiative", project: "TM" },
  { key: "TM-1383", summary: "[쿠폰] [29Connect] 파트너 셀프서브 일반 할인 도입",                         status: "론치완료",       assignee: "양유주",  eta: "2026-03-16", type: "Initiative", project: "TM" },
  { key: "TM-1386", summary: "[파트너] [29CM] 스타벅스 연동 - Phase 1. 상품 등록",                        status: "론치완료",       assignee: "백수지",  eta: "2026-01-09", type: "Initiative", project: "TM" },
  { key: "TM-1420", summary: "[주문] [29CM] 주문 상품/가격 UI UX 개선 - 주문서",                          status: "론치완료",       assignee: "좌예슬",  eta: "2026-01-26", type: "Initiative", project: "TM" },
  { key: "TM-1421", summary: "[채널] [29CM] 셀링툴 연동 정보 제공",                                       status: "론치완료",       assignee: "백수지",  eta: "2026-02-25", type: "Initiative", project: "TM" },
  { key: "TM-1836", summary: "[티켓] [29CM] 공연 정보 통합 관리 어드민 개발 - 좌석 배치도",               status: "론치완료",       assignee: "양유주",  eta: "2026-01-20", type: "Initiative", project: "TM" },
  { key: "TM-1837", summary: "[티켓] [29CM] 예매 취소 기능 고도화 - 지정좌석예매",                        status: "론치완료",       assignee: "양유주",  eta: "2026-01-22", type: "Initiative", project: "TM" },
  { key: "TM-1838", summary: "[티켓] [29CM] 0원 상품 예약 기능 도입 - 지정좌석예매",                      status: "론치완료",       assignee: "양유주",  eta: "2026-02-26", type: "Initiative", project: "TM" },
  { key: "TM-1839", summary: "[티켓] [29CM] 결제혜택 정보 관리 및 제공 - 지정좌석예매",                   status: "론치완료",       assignee: "양유주",  eta: "2026-02-05", type: "Initiative", project: "TM" },
  { key: "TM-1840", summary: "[링펜스] [29CM] KC 인증번호 노출 연동 - PDP",                              status: "론치완료",       assignee: "좌예슬",  eta: "2026-01-13", type: "Initiative", project: "TM" },
  { key: "TM-1842", summary: "[쿠폰] [29Connect] 브랜드 장바구니 쿠폰 도입 & 합구매 넛징",               status: "디자인완료",     assignee: "양유주",  eta: "2026-06-30", type: "Initiative", project: "TM" },
  { key: "TM-1844", summary: "[쿠폰] [29CM] 장바구니 쿠폰가 노출 - PLP/PDP",                             status: "론치완료",       assignee: "정유민",  eta: "2026-03-05", type: "Initiative", project: "TM" },
  { key: "TM-1845", summary: "[결제] [29CM] 무신사페이 도입",                                            status: "QA중",           assignee: "정유민",  eta: "2026-04-21", type: "Initiative", project: "TM",
    roles: [
      { role: "기획",   person: "정유민",   start: "2026-01-12", end: "2026-02-20", status: "완료" },
      { role: "디자인", person: "미정",     start: "2026-02-01", end: "2026-03-15", status: "완료" },
      { role: "개발BE", person: "미정",     start: "2026-03-01", end: "2026-04-15", status: "완료" },
      { role: "개발FE", person: "미정",     start: "2026-03-10", end: "2026-04-15", status: "진행중" },
      { role: "QA",     person: "미정",     start: "2026-04-01", end: "2026-04-21", status: "진행중" },
    ],
  },
  { key: "TM-1846", summary: "[결제] [29CM] 제휴카드 도입",                                              status: "QA중",           assignee: "정유민",  eta: "2026-04-27", type: "Initiative", project: "TM",
    roles: [
      { role: "기획",   person: "정유민",   start: "2026-01-15", end: "2026-02-25", status: "완료" },
      { role: "디자인", person: "미정",     start: "2026-02-10", end: "2026-03-20", status: "완료" },
      { role: "개발BE", person: "미정",     start: "2026-03-01", end: "2026-04-20", status: "진행중" },
      { role: "개발FE", person: "미정",     start: "2026-03-10", end: "2026-04-20", status: "진행중" },
      { role: "QA",     person: "미정",     start: "2026-04-10", end: "2026-04-27", status: "예정" },
    ],
  },
  { key: "TM-1869", summary: "[채널] [29CM] 최저가 노출 개편 - 네이버EP (Q1 연장)",                       status: "QA중",           assignee: "백수지",  eta: "2026-04-13", type: "Initiative", project: "TM" },
  { key: "TM-1871", summary: "[결제] [29CM] 교환 배송비 결제 시스템화",                                   status: "개발중",         assignee: "좌예슬",  eta: "2026-05-11", type: "Initiative", project: "TM" },
  { key: "TM-1872", summary: "[AI] [29CM] PDP 썸네일 영상화 - Iter. 2",                                  status: "론치완료",       assignee: "백수지",  eta: "2026-01-30", type: "Initiative", project: "TM" },
  { key: "TM-1876", summary: "[파트너] [29CM] 스타벅스 연동 - Phase 2. 클레임",                          status: "론치완료",       assignee: "백수지",  eta: "2026-01-26", type: "Initiative", project: "TM" },
  { key: "TM-1885", summary: "[리뷰] [29CM] 도움돼요 피드백 루프 구축",                                   status: "론치완료",       assignee: "백수지",  eta: "2026-02-04", type: "Initiative", project: "TM" },
  { key: "TM-1886", summary: "[리뷰] [29CM] 신고 프로세스 개선 - 사유 인지/정지 해제 (Q1 연장)",          status: "개발중",         assignee: "백수지",  eta: "2026-05-15", type: "Initiative", project: "TM",
    roles: [
      { role: "기획",   person: "백수지",   start: "2026-01-20", end: "2026-02-28", status: "완료" },
      { role: "디자인", person: "미정",     start: "2026-02-20", end: "2026-03-31", status: "완료" },
      { role: "개발BE", person: "미정",     start: "2026-03-15", end: "2026-05-10", status: "진행중" },
      { role: "개발FE", person: "미정",     start: "2026-03-20", end: "2026-05-10", status: "진행중" },
      { role: "QA",     person: "미정",     start: "2026-04-20", end: "2026-05-15", status: "예정" },
    ],
  },
  { key: "TM-1889", summary: "[장바구니] [29CM] 결제할인 추천 넛지",                                      status: "Postponed",      assignee: "정유민",  eta: "2026-06-30", type: "Initiative", project: "TM" },
  { key: "TM-1891", summary: "[주문] [29CM] 주문 상태 정보 불일치 개선 - 마이페이지/주문상세",             status: "론치완료",       assignee: "좌예슬",  eta: "2026-03-13", type: "Initiative", project: "TM" },
  { key: "TM-1892", summary: "[카탈로그] [29CM] 표준카테고리 미매칭 상품 매핑",                           status: "론치완료",       assignee: "백수지",  eta: "2026-04-03", type: "Initiative", project: "TM" },
  { key: "TM-1893", summary: "[카탈로그] [OCMPx29CM] 속성 집계 시스템 구축",                              status: "론치완료",       assignee: "정유민",  eta: "2026-03-31", type: "Initiative", project: "TM" },
  { key: "TM-1900", summary: "[리뷰] [29CM] 초기 리뷰 작성 넛징 도입",                                   status: "론치완료",       assignee: "백수지",  eta: "2026-04-06", type: "Initiative", project: "TM" },
  { key: "TM-1901", summary: "[리뷰] [29Connect] 파트너 펀딩 프로그램 설계 - 초기 리뷰 활성화",           status: "HOLD",           assignee: "백수지",  eta: "2026-04-30", type: "Initiative", project: "TM" },
  { key: "TM-1903", summary: "[링펜스] [29CM] 판매중지 상품 검수 우회 차단",                              status: "론치완료",       assignee: "정유민",  eta: "2026-02-05", type: "Initiative", project: "TM" },
  { key: "TM-1973", summary: "[알림] [29CM] 주문/결제/클레임 알림톡 개선",                                status: "론치완료",       assignee: "좌예슬",  eta: "2026-03-20", type: "Initiative", project: "TM" },
  { key: "TM-2048", summary: "[정산] [OCMPx29CM] 통합 매출 수집/검증 시스템 구축",                        status: "개발중",         assignee: "정윤수",  eta: "2026-04-17", type: "Initiative", project: "TM" },
  { key: "TM-2155", summary: "[CS] [OCMPx29CM] AI 상담사 채팅 도입 - Omni-Channel",                      status: "Postponed",      assignee: "좌예슬",  eta: "2026-09-30", type: "Initiative", project: "TM" },
  { key: "TM-2174", summary: "[쿠폰] [29CM] 카테고리 재구매 쿠폰 - 이구홈위크",                           status: "론치완료",       assignee: "양유주",  eta: "2026-02-11", type: "Initiative", project: "TM" },
  { key: "TM-2182", summary: "[채널] [29CM] 단위가격 표시제 적용 - 네이버EP",                             status: "기획중",         assignee: "백수지",  eta: "2026-06-30", type: "Initiative", project: "TM" },
  { key: "TM-2185", summary: "[보안] [29CM] OpenAPI 전환 - V1 to V2",                                    status: "론치완료",       assignee: "백수지",  eta: "2026-03-27", type: "Initiative", project: "TM" },
  { key: "TM-2186", summary: "[정책] [29CM] 국회상생안 대응 - 브랜드 수수료 인하",                        status: "론치완료",       assignee: "정유민",  eta: "2026-03-12", type: "Initiative", project: "TM" },
  { key: "TM-2216", summary: "[카탈로그] [OCMPx29CM] 매입 브랜드 공급업체 식별 체계 개선",                status: "론치완료",       assignee: "좌예슬",  eta: "2026-03-03", type: "Initiative", project: "TM" },
  { key: "TM-2234", summary: "[링펜스] [29CM] 상품 검수 운영 편의성 개선",                                status: "론치완료",       assignee: "정유민",  eta: "2026-02-25", type: "Initiative", project: "TM" },
  { key: "TM-2294", summary: "[리뷰] [29CM] 적립금 차등 지급 정책 개편 - HF",                            status: "론치완료",       assignee: "백수지",  eta: "2026-03-25", type: "Initiative", project: "TM" },
  // TM Q2
  { key: "TM-2513", summary: "[이구위크] 쿠폰 발급 프로세스 개선",                                        status: "개발중",         assignee: "윤정오",  eta: "2026-05-12", type: "Initiative", project: "TM" },
  { key: "TM-2726", summary: "[이구위크] 카테고리 첫구매 쿠폰 로직 고도화",                                status: "SUGGESTED",      assignee: "-",       eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2727", summary: "[이구위크] 브랜드 첫구매 쿠폰 기능 및 모듈화",                              status: "준비중",         assignee: "양유주",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2741", summary: "[티켓 내재화] 좌석 선점/해제 모듈 내재화",                                   status: "개발중",         assignee: "강행남",  eta: "2026-05-14", type: "Initiative", project: "TM" },
  { key: "TM-2742", summary: "[티켓 내재화] 대기열 내재화",                                                status: "준비중",         assignee: "강행남",  eta: "2026-05-29", type: "Initiative", project: "TM" },
  { key: "TM-2745", summary: "[결제] 케이뱅크 할인혜택 넛징",                                             status: "SUGGESTED",      assignee: "정유민",  eta: "2026-07-20", type: "Initiative", project: "TM" },
  { key: "TM-2746", summary: "[파트너] 큐레이터 상품 시딩 캠페인 - 무료주문 생성",                         status: "개발중",         assignee: "정유민",  eta: "2026-05-29", type: "Initiative", project: "TM" },
  { key: "TM-2751", summary: "[CS] AI Chat Agent 1:1문의 진입점 A/B 테스트",                               status: "SUGGESTED",      assignee: "좌예슬",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2753", summary: "[CS] CS 상담 Agent Workspace 도입",                                         status: "SUGGESTED",      assignee: "좌예슬",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2756", summary: "[OCMP] 통합 상품등록 어드민 요구사항 수집 설계 - 29CM",                      status: "기획중",         assignee: "정유민",  eta: "2026-07-31", type: "Initiative", project: "TM" },
  { key: "TM-2758", summary: "[카탈로그] 표준카테고리 미매칭 상품 매핑",                                   status: "SUGGESTED",      assignee: "백수지",  eta: "2026-06-30", type: "Initiative", project: "TM" },
  { key: "TM-2762", summary: "네이버 EP: Phase 2. 매핑율 향상",                                           status: "Backlog",        assignee: "-",       eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2763", summary: "쿠폰 전시가격 미노출 브랜드 설정 기능(블랙리스트) 개선",                     status: "디자인중",       assignee: "정유민",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2770", summary: "[클레임] N회차 교환 로직 개선",                                              status: "Backlog",        assignee: "-",       eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2771", summary: "[OCMP] AI Chat agent 상담사 채팅 기능 도입",                                 status: "SUGGESTED",      assignee: "-",       eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2779", summary: "[CS] CS 상담 CRM 도입 (w/ Salesforce, 파트너 Office)",                      status: "SUGGESTED",      assignee: "좌예슬",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2814", summary: "SRP, PLP 퀵패싯(브랜드,컬러) 고객향 UI/UX 개선",                            status: "디자인완료",     assignee: "이현욱",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2815", summary: "[티켓 내재화] 좌석 배치도 사용성 개선",                                      status: "개발중",         assignee: "강행남",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2817", summary: "무신사트레이딩 합병 : 물류/ERP(SAP) 연동 마스터 정리",                       status: "개발중",         assignee: "윤정오",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2853", summary: "[카탈로그] [SCM Hub] O-SKU 전환 대응 29CM 상품등록 내부 API 신설",            status: "개발중",         assignee: "좌예슬",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2854", summary: "[파트너] [29Connect] 매입 상품 수기 재고 차감 기능 도입 - 나이키 반출 대응",  status: "SUGGESTED",      assignee: "좌예슬",  eta: "-",          type: "Initiative", project: "TM" },
  { key: "TM-2878", summary: "29CM EP 송출 상품 중 카탈로그 자동맵핑 상품 비중 개선",                       status: "SUGGESTED",      assignee: "최민주",  eta: "-",          type: "Initiative", project: "TM" },
  // CMALL
  { key: "CMALL-507",  summary: "인터페이스 일관성 기준 위반을 자동 검수하는 플러그인 제작 PoC",            status: "배포완료",       assignee: "윤민희",  eta: "2025-12-30", type: "Initiative", project: "CMALL" },
  { key: "CMALL-519",  summary: "25'Q4 29CM KTLO",                                                        status: "론치완료",       assignee: "김영진",  eta: "2025-12-31", type: "Initiative", project: "CMALL" },
  { key: "CMALL-520",  summary: "25'Q4 29CM Urgent",                                                      status: "개발중",         assignee: "김효진",  eta: "2025-12-31", type: "Initiative", project: "CMALL" },
  { key: "CMALL-521",  summary: "25'Q4 29CM BAU",                                                         status: "개발중",         assignee: "김효진",  eta: "2025-12-31", type: "Initiative", project: "CMALL" },
  { key: "CMALL-539",  summary: "29cm 고객의 소리 문의 유형 추가 및 수정 요청",                            status: "SUGGESTED",      assignee: "김지수",  eta: "2025-10-24", type: "Initiative", project: "CMALL" },
  { key: "CMALL-546",  summary: "[뷰티팀] 입점 브랜드사 api 연동 Q&A 질의 확인 요청",                     status: "SUGGESTED",      assignee: "김영진",  eta: "2025-10-24", type: "Initiative", project: "CMALL" },
  { key: "CMALL-549",  summary: "[커머스] 아크테릭스(위탁브랜드) 교환불가/반품ONLY 기능 추가",             status: "론치완료",       assignee: "강민우",  eta: "-",          type: "Initiative", project: "CMALL" },
  { key: "CMALL-567",  summary: "[커머스] 라이카(위탁브랜드) 교환불가/반품ONLY 기능 추가",                 status: "SUGGESTED",      assignee: "-",       eta: "-",          type: "Initiative", project: "CMALL" },
  { key: "CMALL-593",  summary: "[Mitosis] 프라이빗 메시 네트워크 환경 비용 효율화/보안 강화",             status: "론치완료",       assignee: "송정훈",  eta: "2026-03-06", type: "Initiative", project: "CMALL" },
  { key: "CMALL-594",  summary: "[Mitosis] Mother(Angular) → React 전환 Phase 1",                         status: "개발중",         assignee: "이한준",  eta: "2026-05-29", type: "Initiative", project: "CMALL" },
  { key: "CMALL-605",  summary: "[29CM] 26'Q1 KTLO",                                                      status: "론치완료",       assignee: "김영진",  eta: "2026-04-03", type: "Initiative", project: "CMALL" },
  { key: "CMALL-609",  summary: "[Mitosis] Shadow Traffic Compare System 개발",                           status: "론치완료",       assignee: "이한준",  eta: "2026-01-30", type: "Initiative", project: "CMALL" },
  { key: "CMALL-610",  summary: "[Mitosis] Near-Zero Downtime DB Switching System 개발",                  status: "QA중",           assignee: "이한준",  eta: "2026-04-09", type: "Initiative", project: "CMALL" },
  { key: "CMALL-616",  summary: "[29CM] 26'Q1 Urgent",                                                    status: "개발중",         assignee: "김효진",  eta: "2026-04-03", type: "Initiative", project: "CMALL" },
  { key: "CMALL-618",  summary: "[Mitosis] Promotion API Migration (Django → Spring)",                    status: "론치완료",       assignee: "이한준",  eta: "2026-03-27", type: "Initiative", project: "CMALL" },
  { key: "CMALL-620",  summary: "[Mitosis] Promotion API Outbound Implement",                             status: "론치완료",       assignee: "이한준",  eta: "2026-03-26", type: "Initiative", project: "CMALL" },
  { key: "CMALL-622",  summary: "[Mitosis] DB Migration Library 적용",                                    status: "철회/반려/취소", assignee: "이양호",  eta: "2026-03-27", type: "Initiative", project: "CMALL" },
  { key: "CMALL-693",  summary: "1:1문의 첨부 파일 확대 (2개 → 6개)",                                    status: "론치완료",       assignee: "좌예슬",  eta: "2026-02-06", type: "Initiative", project: "CMALL" },
  { key: "CMALL-735",  summary: "[Mitosis] Mother(Angular) → React 전환 Phase 2",                        status: "SUGGESTED",      assignee: "이한준",  eta: "2026-06-19", type: "Initiative", project: "CMALL" },
  { key: "CMALL-746",  summary: "[Mitosis] 29Connect FE 레거시 전환 Phase 2",                             status: "SUGGESTED",      assignee: "이한준",  eta: "-",          type: "Initiative", project: "CMALL" },
  { key: "CMALL-747",  summary: "[Mitosis] Review 서비스 분리",                                           status: "개발중",         assignee: "이한준",  eta: "2026-05-06", type: "Initiative", project: "CMALL" },
  { key: "CMALL-748",  summary: "[Mitosis] Like 서비스 분리",                                             status: "개발중",         assignee: "이한준",  eta: "2026-05-18", type: "Initiative", project: "CMALL" },
  { key: "CMALL-749",  summary: "[Mitosis] Moment Trigger 서비스 분리",                                   status: "개발중",         assignee: "이한준",  eta: "2026-04-23", type: "Initiative", project: "CMALL" },
  { key: "CMALL-770",  summary: "모노하 3월 추가 수수료 보정 요청 건",                                    status: "SUGGESTED",      assignee: "강세종",  eta: "2026-03-31", type: "Initiative", project: "CMALL" },
];
